jwt:
  secret: my_super_secret_jwt_key_2025_identity_service
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db
    username: identity-service
    password: identity-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
